### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: Conv2DCustomBackpropInputOp only supports NHWC.

### ISSUE THREAD

**Issue by c1a1o1** [JeremyCCHsu/vae-npvc#17]
tensorflow.python.framework.errors_impl.InvalidArgumentError: Conv2DCustomBackpropInputOp only supports NHWC.
	 [[{{node Update/gradients/loss/Encoder/Conv2d-4/Conv2d-4/Conv2D_grad/Conv2DBackpropInput}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:/work/vae-npvc-master/main.py", line 78, in <module>
    main()
  File "F:/work/vae-npvc-master/main.py", line 74, in main
    trainer.train(nIter=arch['training']['max_iter'], machine=machine)
  File "F:\work\vae-npvc-master\trainer\vae.py", line 99, in train
    sess.run(self.opt['g'])
  File "F:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 950, in run
    run_metadata_ptr)
  File "F:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "F:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1350, in _do_run
    run_metadata)

**Comment by bruceloco** [comment]
install intel-tensorflow if you are using intelcpu
